# Generated by Django 5.1.4 on 2024-12-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaaddress',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usaaddress',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
