# Generated by Django 5.1.4 on 2024-12-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='სახელი')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='კოდი')),
                ('transporting_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ტრანსპორტირების საფასური')),
            ],
            options={
                'verbose_name': 'ქვეყანა',
                'verbose_name_plural': 'ქვეყნები',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='დასახელება')),
            ],
            options={
                'verbose_name': 'ვალუტა',
                'verbose_name_plural': 'ვალუტები',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='სტატუსი')),
            ],
            options={
                'verbose_name_plural': 'სტატუსი',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(verbose_name='გამოფრენის თარიღი')),
                ('estimated_arrival_date', models.DateField(verbose_name='ჩამოფრენის სავარაუდო თარიღი')),
                ('arrival_date', models.DateField(verbose_name='ჩამოფრენის თარიღი')),
                ('flight_number', models.CharField(editable=False, max_length=10, unique=True, verbose_name='რეისის ნომერი')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='სტატუსი')),
            ],
            options={
                'verbose_name': 'რეისი',
                'verbose_name_plural': 'რეისები',
            },
        ),
    ]
