# Generated by Django 5.1.4 on 2024-12-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_currency_status_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaaddress',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AddField(
            model_name='usaaddress',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='ჩამოფრენის თარიღი'),
        ),
    ]
