# Generated by Django 5.1.4 on 2024-12-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chinaaddress_price_alter_usaaddress_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinaaddress',
            name='price',
        ),
        migrations.RemoveField(
            model_name='usaaddress',
            name='price',
        ),
    ]
