# Generated by Django 5.1.4 on 2024-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_price_chinaaddress_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='transporting_fee',
        ),
        migrations.AddField(
            model_name='country',
            name='transporting_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ტრანსპორტირების ფასი'),
        ),
    ]
