# Generated by Django 5.1.4 on 2024-12-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chinaaddress_price_remove_usaaddress_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinaaddress',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='usaaddress',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
