# Generated by Django 5.1.4 on 2024-12-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chinaaddress_price_usaaddress_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaaddress',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='usaaddress',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
