# Generated by Django 5.1.4 on 2024-12-14 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_country_currency_status_flight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='დასახელება')),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=100, unique=True, verbose_name='თრექინგი')),
                ('online_store', models.CharField(max_length=100, verbose_name='ონლაინ მაღაზია')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('delivery_time', models.DateField(verbose_name='ჩაბარების თარიღი')),
                ('taken_time', models.DateField(verbose_name='გატანის თარიღი')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='წონა')),
                ('custom_clearance', models.BooleanField(default=False, verbose_name='განბაჟება')),
                ('is_paid', models.BooleanField(default=False, verbose_name='გადახდილია')),
                ('transporting_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ტრანსპორტირების ფასი')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='ფილიალი')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel.category', verbose_name='კატეგორია')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country', verbose_name='ქვეყანა')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='ვალუტა')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flight', verbose_name='რეისი')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.status', verbose_name='სტატუსი')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი')),
            ],
            options={
                'verbose_name': 'ამანათი',
                'verbose_name_plural': 'ამანათები',
            },
        ),
    ]
