# Generated by Django 5.1.4 on 2024-12-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='transporting_price',
        ),
        migrations.AddField(
            model_name='parcel',
            name='transporting_fee',
            field=models.DecimalField(decimal_places=2, default='12.5', max_digits=5, verbose_name='ტრანსპორტირების საფასური'),
            preserve_default=False,
        ),
    ]
