# Generated by Django 5.1.4 on 2024-12-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_remove_parcel_transporting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='დასახელება'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='transporting_fee',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='ტრანსპორტირების საფასური'),
        ),
    ]
