# Generated by Django 5.1.4 on 2024-12-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_country_transporting_fee_and_more'),
        ('parcel', '0003_alter_category_name_alter_parcel_transporting_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='ფილიალი'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='ვალუტა'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.flight', verbose_name='რეისი'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='online_store',
            field=models.CharField(blank=True, max_length=100, verbose_name='ონლაინ მაღაზია'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='ფასი'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='taken_time',
            field=models.DateField(blank=True, null=True, verbose_name='გატანის თარიღი'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='წონა'),
        ),
    ]
