# Generated by Django 5.1.4 on 2024-12-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0004_alter_parcel_branch_alter_parcel_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ფასი'),
        ),
    ]
