# Generated by Django 5.1.4 on 2024-12-17 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0005_alter_parcel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_declared',
            field=models.BooleanField(default=False, verbose_name='დეკლარირებულია'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcel.category', verbose_name='კატეგორია'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='transporting_fee',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='ტრ. საფასური'),
        ),
    ]
