# Generated by Django 5.1.4 on 2024-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0006_parcel_is_declared_alter_parcel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_time',
            field=models.DateField(auto_now_add=True, verbose_name='ჩაბარების თარიღი'),
        ),
    ]
